#!/usr/bin/env bash
# =============================================================================
# Generate AGENTS.md - Build passive context from profile + library catalog
# =============================================================================
# Reads device profile and library.json to generate a context file that
# Claude Code loads automatically in every session.
#
# Output: $ADMIN_ROOT/generated/AGENTS.md + ~/.claude/AGENTS.md (symlink/copy)
#
# Usage:
#   generate-agents-md.sh             # Generate and install
#   generate-agents-md.sh --dry-run   # Print to stdout
# =============================================================================

set -euo pipefail

SATELLITE_ENV="${HOME}/.admin/.env"
resolve_admin_root() {
    if [[ -n "${ADMIN_ROOT:-}" ]]; then echo "$ADMIN_ROOT"; return; fi
    if [[ -f "$SATELLITE_ENV" ]]; then
        local root; root=$(grep "^ADMIN_ROOT=" "$SATELLITE_ENV" 2>/dev/null | head -1 | cut -d'=' -f2-)
        if [[ -n "$root" ]]; then echo "$root"; return; fi
    fi
    echo "${HOME}/.admin"
}
resolve_device_name() {
    if [[ -n "${ADMIN_DEVICE:-}" ]]; then echo "$ADMIN_DEVICE"; return; fi
    if [[ -f "$SATELLITE_ENV" ]]; then
        local dev; dev=$(grep "^ADMIN_DEVICE=" "$SATELLITE_ENV" 2>/dev/null | head -1 | cut -d'=' -f2-)
        if [[ -n "$dev" ]]; then echo "$dev"; return; fi
    fi
    hostname
}

ADMIN_ROOT="$(resolve_admin_root)"
DEVICE_NAME="$(resolve_device_name)"
PROFILE_PATH="${ADMIN_ROOT}/profiles/${DEVICE_NAME}.json"
LIBRARY_JSON="${LIBRARY_JSON_PATH:-${HOME}/.claude/skills/library/library.json}"
GENERATED_DIR="${ADMIN_ROOT}/generated"
OUTPUT_FILE="${GENERATED_DIR}/AGENTS.md"
CLAUDE_AGENTS="${HOME}/.claude/AGENTS.md"
SENTINEL="<!-- generated by generate-agents-md.sh -->"

DRY_RUN=false
[[ "${1:-}" == "--dry-run" ]] && DRY_RUN=true

if ! command -v jq &>/dev/null; then echo "Error: jq required" >&2; exit 1; fi
if [[ ! -f "$PROFILE_PATH" ]]; then echo "Error: Profile not found: $PROFILE_PATH" >&2; exit 1; fi

# Read profile
CONSUMER_TYPE=$(jq -r '.consumer.type // "workstation"' "$PROFILE_PATH")
TRUST_BOUNDARY=$(jq -r '.consumer.trustBoundary // "operator"' "$PROFILE_PATH")
PLATFORM=$(jq -r '.device.platform // "unknown"' "$PROFILE_PATH")
OS=$(jq -r '.device.os // "unknown"' "$PROFILE_PATH")
TOOL_COUNT=$(jq '.tools | length' "$PROFILE_PATH" 2>/dev/null || echo 0)
SERVER_COUNT=$(jq '.servers | length' "$PROFILE_PATH" 2>/dev/null || echo 0)

# Build the markdown
generate() {
    echo "$SENTINEL"
    echo "# Device Context: $DEVICE_NAME"
    echo ""
    echo "| Property | Value |"
    echo "|----------|-------|"
    echo "| Device | $DEVICE_NAME |"
    echo "| Platform | $PLATFORM ($OS) |"
    echo "| Consumer | $CONSUMER_TYPE |"
    echo "| Trust | $TRUST_BOUNDARY |"
    echo "| Tools | $TOOL_COUNT registered |"
    echo "| Servers | $SERVER_COUNT managed |"
    echo ""

    # Skills section (from library if available)
    if [[ -f "$LIBRARY_JSON" ]]; then
        echo "## Installed Skills"
        echo ""
        echo "| Skill | Description |"
        echo "|-------|-------------|"
        local skill_count
        skill_count=$(jq '.library.skills | length' "$LIBRARY_JSON" 2>/dev/null || echo 0)
        for ((i = 0; i < skill_count; i++)); do
            local name desc targets
            name=$(jq -r ".library.skills[$i].name" "$LIBRARY_JSON")
            desc=$(jq -r ".library.skills[$i].description" "$LIBRARY_JSON")
            targets=$(jq -r ".library.skills[$i].targets | join(\",\")" "$LIBRARY_JSON")
            # Only show entries that target this consumer type
            if [[ ",$targets," == *",$CONSUMER_TYPE,"* ]]; then
                echo "| $name | $desc |"
            fi
        done
        echo ""

        # Agents section
        local agent_count
        agent_count=$(jq '.library.agents | length' "$LIBRARY_JSON" 2>/dev/null || echo 0)
        if [[ "$agent_count" -gt 0 ]]; then
            echo "## Available Agents"
            echo ""
            echo "| Agent | Description |"
            echo "|-------|-------------|"
            for ((i = 0; i < agent_count; i++)); do
                local name desc targets
                name=$(jq -r ".library.agents[$i].name" "$LIBRARY_JSON")
                desc=$(jq -r ".library.agents[$i].description" "$LIBRARY_JSON")
                targets=$(jq -r ".library.agents[$i].targets | join(\",\")" "$LIBRARY_JSON")
                if [[ ",$targets," == *",$CONSUMER_TYPE,"* ]]; then
                    echo "| $name | $desc |"
                fi
            done
            echo ""
        fi

        # Commands section
        local prompt_count
        prompt_count=$(jq '.library.prompts | length' "$LIBRARY_JSON" 2>/dev/null || echo 0)
        if [[ "$prompt_count" -gt 0 ]]; then
            echo "## Slash Commands"
            echo ""
            echo "| Command | Description |"
            echo "|---------|-------------|"
            for ((i = 0; i < prompt_count; i++)); do
                local name desc targets
                name=$(jq -r ".library.prompts[$i].name" "$LIBRARY_JSON")
                desc=$(jq -r ".library.prompts[$i].description" "$LIBRARY_JSON")
                targets=$(jq -r ".library.prompts[$i].targets | join(\",\")" "$LIBRARY_JSON")
                if [[ ",$targets," == *",$CONSUMER_TYPE,"* ]]; then
                    echo "| /$name | $desc |"
                fi
            done
            echo ""
        fi

        # MCP section
        local mcp_count
        mcp_count=$(jq '.library.mcp | length' "$LIBRARY_JSON" 2>/dev/null || echo 0)
        if [[ "$mcp_count" -gt 0 ]]; then
            echo "## MCP Servers"
            echo ""
            echo "| Server | Description | Status |"
            echo "|--------|-------------|--------|"
            for ((i = 0; i < mcp_count; i++)); do
                local name desc targets status
                name=$(jq -r ".library.mcp[$i].name" "$LIBRARY_JSON")
                desc=$(jq -r ".library.mcp[$i].description" "$LIBRARY_JSON")
                targets=$(jq -r ".library.mcp[$i].targets | join(\",\")" "$LIBRARY_JSON")
                status=$(jq -r ".bindings.mcp[\"$name\"].status // \"not bound\"" "$PROFILE_PATH" 2>/dev/null)
                if [[ ",$targets," == *",$CONSUMER_TYPE,"* ]]; then
                    echo "| $name | $desc | $status |"
                fi
            done
            echo ""
        fi
    fi

    # Access scope
    local projects
    projects=$(jq -r '.access.projects // [] | join(", ")' "$PROFILE_PATH" 2>/dev/null)
    if [[ -n "$projects" ]]; then
        echo "## Access Scope"
        echo ""
        echo "- **Infisical projects**: $projects"
        echo "- **Trust boundary**: $TRUST_BOUNDARY"
        echo ""
    fi
}

if [[ "$DRY_RUN" == "true" ]]; then
    generate
else
    mkdir -p "$GENERATED_DIR"
    generate > "$OUTPUT_FILE"
    echo "Generated: $OUTPUT_FILE"

    # Install to ~/.claude/AGENTS.md (where Claude Code reads it)
    if [[ -f "$CLAUDE_AGENTS" ]]; then
        # Check if it's our generated file (sentinel check)
        if head -1 "$CLAUDE_AGENTS" 2>/dev/null | grep -q "generate-agents-md.sh"; then
            cp "$OUTPUT_FILE" "$CLAUDE_AGENTS"
            echo "Updated: $CLAUDE_AGENTS"
        else
            echo "Warning: $CLAUDE_AGENTS exists but was not generated by us. Skipping."
            echo "  To overwrite, delete it first: rm $CLAUDE_AGENTS"
        fi
    else
        cp "$OUTPUT_FILE" "$CLAUDE_AGENTS"
        echo "Installed: $CLAUDE_AGENTS"
    fi
fi
