#!/usr/bin/env bash
# =============================================================================
# Render Runtime - Resolve all secretRefs/fileRefs and generate output files
# =============================================================================
# Orchestrator that loads the device profile, resolves all infisical:// URIs
# in secretRefs and fileRefs, and writes generated output files:
#   - $ADMIN_ROOT/generated/.env       (resolved secrets as KEY=value)
#   - $ADMIN_ROOT/generated/compat.env (legacy-compatible flat KEY=value)
#   - $ADMIN_ROOT/generated/*.json     (rendered credential files)
#
# Usage:
#   ./render-runtime.sh                  # Full render
#   ./render-runtime.sh --dry-run        # Show what would be resolved
#   ./render-runtime.sh --env prod       # Specify environment
#   ./render-runtime.sh --refs-only      # Only resolve secretRefs, skip fileRefs
# =============================================================================

set -euo pipefail

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
CYAN='\033[0;36m'
NC='\033[0m'

info() { echo -e "${CYAN}[i]${NC} $1"; }
ok() { echo -e "${GREEN}[OK]${NC} $1"; }
warn() { echo -e "${YELLOW}[!]${NC} $1"; }
err() { echo -e "${RED}[-]${NC} $1"; }
section() { echo -e "\n${CYAN}=== $1 ===${NC}"; }

SATELLITE_ENV="${HOME}/.admin/.env"

resolve_admin_root() {
    if [[ -n "${ADMIN_ROOT:-}" ]]; then echo "$ADMIN_ROOT"; return; fi
    if [[ -f "$SATELLITE_ENV" ]]; then
        local root
        root=$(grep "^ADMIN_ROOT=" "$SATELLITE_ENV" 2>/dev/null | head -1 | cut -d'=' -f2-)
        if [[ -n "$root" ]]; then echo "$root"; return; fi
    fi
    echo "${HOME}/.admin"
}

resolve_device_name() {
    if [[ -n "${ADMIN_DEVICE:-}" ]]; then echo "$ADMIN_DEVICE"; return; fi
    if [[ -f "$SATELLITE_ENV" ]]; then
        local dev
        dev=$(grep "^ADMIN_DEVICE=" "$SATELLITE_ENV" 2>/dev/null | head -1 | cut -d'=' -f2-)
        if [[ -n "$dev" ]]; then echo "$dev"; return; fi
    fi
    hostname
}

ADMIN_ROOT="$(resolve_admin_root)"
DEVICE_NAME="$(resolve_device_name)"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROFILE_PATH="${ADMIN_ROOT}/profiles/${DEVICE_NAME}.json"
GENERATED_DIR="${ADMIN_ROOT}/generated"

DRY_RUN=false
REFS_ONLY=false
SKIP_UNRESOLVABLE=false

while [[ $# -gt 0 ]]; do
    case "$1" in
        --dry-run) DRY_RUN=true; shift ;;
        --refs-only) REFS_ONLY=true; shift ;;
        --skip-unresolvable) SKIP_UNRESOLVABLE=true; shift ;;
        -h|--help)
            echo "Usage: render-runtime.sh [--dry-run] [--refs-only] [--skip-unresolvable]"
            exit 0
            ;;
        *) err "Unknown: $1"; exit 1 ;;
    esac
done

if ! command -v jq &>/dev/null; then err "jq required"; exit 1; fi
if [[ ! -f "$PROFILE_PATH" ]]; then err "Profile not found: $PROFILE_PATH"; exit 1; fi

section "Render Runtime"
info "Profile: $PROFILE_PATH"
info "Output:  $GENERATED_DIR"

# Create generated directory
if [[ "$DRY_RUN" != "true" ]]; then
    mkdir -p "$GENERATED_DIR"
fi

# --- Resolve secretRefs ---
section "Resolving secretRefs"

ENV_FILE="${GENERATED_DIR}/.env"
COMPAT_FILE="${GENERATED_DIR}/compat.env"

resolved=0
failed=0

# Start fresh env files
if [[ "$DRY_RUN" != "true" ]]; then
    echo "# Generated by render-runtime.sh at $(date -u +%Y-%m-%dT%H:%M:%SZ)" > "$ENV_FILE"
    echo "# DO NOT EDIT - regenerate with: render-runtime.sh" >> "$ENV_FILE"
    echo "" >> "$ENV_FILE"

    echo "# Legacy-compatible flat secrets (generated)" > "$COMPAT_FILE"
    echo "# Maps infisical:// URIs back to original flat key names" >> "$COMPAT_FILE"
    echo "" >> "$COMPAT_FILE"
fi

# Read secretRefs from bindings (v4.1) — all component types
bindings_refs=$(jq -r '
    .bindings // {} | to_entries[] | .value | to_entries[] |
    select(.value.secretRefs != null) |
    .value.secretRefs | to_entries[] | "\(.key)=\(.value)"
' "$PROFILE_PATH" 2>/dev/null || true)

# Also read flat secretRefs (v4.0 backward compat)
flat_refs=$(jq -r '.secretRefs // {} | to_entries[] | "\(.key)=\(.value)"' "$PROFILE_PATH" 2>/dev/null || true)

# Combine: bindings first (take precedence), then flat
all_refs=""
[[ -n "$bindings_refs" ]] && all_refs+="$bindings_refs"$'\n'
[[ -n "$flat_refs" ]] && all_refs+="$flat_refs"

# Deduplicate (first occurrence wins = bindings win)
declare -A seen_keys
while IFS='=' read -r ref_name ref_uri; do
    [[ -z "$ref_name" ]] && continue
    [[ -n "${seen_keys[$ref_name]:-}" ]] && continue
    seen_keys[$ref_name]=1

    echo -n "  $ref_name... "

    if [[ "$DRY_RUN" == "true" ]]; then
        echo "$ref_uri"
        resolved=$((resolved + 1))
        continue
    fi

    value=$("$SCRIPT_DIR/resolve-secret-ref.sh" --quiet "$ref_uri" 2>/dev/null || true)
    if [[ -n "$value" ]]; then
        echo "${ref_name}=${value}" >> "$ENV_FILE"
        flat_key=$(echo "$ref_uri" | rev | cut -d'/' -f1 | rev)
        echo "${flat_key}=${value}" >> "$COMPAT_FILE"
        echo "OK"
        resolved=$((resolved + 1))
    else
        if [[ "$SKIP_UNRESOLVABLE" == "true" ]]; then
            echo "# UNRESOLVED: ${ref_name}" >> "$ENV_FILE"
            echo "PENDING (skip-unresolvable)"
            resolved=$((resolved + 1))
        else
            echo "FAILED"
            failed=$((failed + 1))
        fi
    fi
done <<< "$all_refs"

# --- Also resolve deployment secretRefs ---
deploy_refs=$(jq -r '
    .deployments // {} | to_entries[] |
    select(.value.secretRefs != null) |
    .value.secretRefs | to_entries[] |
    "\(.key)=\(.value)"
' "$PROFILE_PATH" 2>/dev/null || true)

if [[ -n "$deploy_refs" ]]; then
    section "Resolving deployment secretRefs"
    while IFS='=' read -r ref_name ref_uri; do
        [[ -z "$ref_name" ]] && continue

        echo -n "  $ref_name... "

        if [[ "$DRY_RUN" == "true" ]]; then
            echo "$ref_uri"
            resolved=$((resolved + 1))
            continue
        fi

        value=$("$SCRIPT_DIR/resolve-secret-ref.sh" --quiet "$ref_uri" 2>/dev/null || true)
        if [[ -n "$value" ]]; then
            echo "${ref_name}=${value}" >> "$ENV_FILE"
            flat_key=$(echo "$ref_uri" | rev | cut -d'/' -f1 | rev)
            echo "${flat_key}=${value}" >> "$COMPAT_FILE"
            echo "OK"
            resolved=$((resolved + 1))
        else
            echo "FAILED"
            failed=$((failed + 1))
        fi
    done <<< "$deploy_refs"
fi

# --- Resolve fileRefs ---
if [[ "$REFS_ONLY" != "true" ]]; then
    file_refs=$(jq -r '.fileRefs // {} | to_entries[] | "\(.key)=\(.value.uri)|\(.value.renderTo)"' "$PROFILE_PATH" 2>/dev/null || true)

    if [[ -n "$file_refs" ]]; then
        section "Resolving fileRefs"
        while IFS='=' read -r ref_name ref_spec; do
            [[ -z "$ref_name" ]] && continue
            IFS='|' read -r ref_uri render_to <<< "$ref_spec"

            echo -n "  $ref_name -> $render_to... "

            if [[ "$DRY_RUN" == "true" ]]; then
                echo "$ref_uri"
                resolved=$((resolved + 1))
                continue
            fi

            if "$SCRIPT_DIR/render-secret-file.sh" "$ref_uri" "$render_to" 2>/dev/null; then
                echo "OK"
                resolved=$((resolved + 1))
            else
                echo "FAILED"
                failed=$((failed + 1))
            fi
        done <<< "$file_refs"
    fi
fi

# Set permissions on generated files
if [[ "$DRY_RUN" != "true" ]]; then
    chmod 600 "$ENV_FILE" "$COMPAT_FILE" 2>/dev/null || true
fi

section "Render Summary"
echo "Resolved: $resolved"
echo "Failed:   $failed"
if [[ "$DRY_RUN" != "true" ]]; then
    echo ""
    echo "Generated files:"
    echo "  $ENV_FILE"
    echo "  $COMPAT_FILE"
fi

if [[ "$DRY_RUN" == "true" ]]; then
    warn "This was a dry run."
fi
