#Requires -Version 5.1
<#
.SYNOPSIS
    Render Runtime - Resolve all secretRefs/fileRefs and generate output files
.DESCRIPTION
    Loads device profile, resolves all infisical:// URIs in secretRefs/fileRefs,
    writes generated output files.
.PARAMETER DryRun
    Show what would be resolved without writing
.PARAMETER RefsOnly
    Only resolve secretRefs, skip fileRefs
.EXAMPLE
    .\Render-Runtime.ps1
    .\Render-Runtime.ps1 -DryRun
#>

[CmdletBinding()]
param(
    [switch]$DryRun,
    [switch]$RefsOnly
)

$ErrorActionPreference = "Stop"

# --- Resolve paths ---
function Get-AdminRoot {
    if ($env:ADMIN_ROOT) { return $env:ADMIN_ROOT }
    $satelliteEnv = Join-Path $HOME ".admin\.env"
    if (Test-Path $satelliteEnv) {
        $match = Select-String -Path $satelliteEnv -Pattern "^ADMIN_ROOT=(.+)$" | Select-Object -First 1
        if ($match) { return $match.Matches.Groups[1].Value }
    }
    return Join-Path $HOME ".admin"
}

function Get-DeviceName {
    if ($env:ADMIN_DEVICE) { return $env:ADMIN_DEVICE }
    $satelliteEnv = Join-Path $HOME ".admin\.env"
    if (Test-Path $satelliteEnv) {
        $match = Select-String -Path $satelliteEnv -Pattern "^ADMIN_DEVICE=(.+)$" | Select-Object -First 1
        if ($match) { return $match.Matches.Groups[1].Value }
    }
    return $env:COMPUTERNAME
}

$AdminRoot = Get-AdminRoot
$DeviceName = Get-DeviceName
$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$ProfilePath = Join-Path $AdminRoot "profiles\$DeviceName.json"
$GeneratedDir = Join-Path $AdminRoot "generated"

if (-not (Test-Path $ProfilePath)) {
    Write-Error "Profile not found: $ProfilePath"
    exit 1
}

Write-Host "=== Render Runtime ===" -ForegroundColor Cyan
Write-Host "Profile: $ProfilePath"
Write-Host "Output:  $GeneratedDir"

# Create generated directory
if (-not $DryRun -and -not (Test-Path $GeneratedDir)) {
    $null = New-Item -ItemType Directory -Path $GeneratedDir -Force
}

$profile = Get-Content $ProfilePath -Raw | ConvertFrom-Json
$resolved = 0
$failed = 0

# --- Resolve secretRefs ---
Write-Host "`n=== Resolving secretRefs ===" -ForegroundColor Cyan

$envLines = @("# Generated by Render-Runtime.ps1 at $(Get-Date -Format o)", "# DO NOT EDIT", "")
$compatLines = @("# Legacy-compatible flat secrets (generated)", "")

if ($profile.secretRefs) {
    foreach ($prop in $profile.secretRefs.PSObject.Properties) {
        $refName = $prop.Name
        $refUri = $prop.Value

        Write-Host -NoNewline "  $refName... "

        if ($DryRun) {
            Write-Host $refUri
            $resolved++
            continue
        }

        try {
            $value = & "$ScriptDir\Resolve-SecretRef.ps1" $refUri -Quiet 2>$null
            if ($value) {
                $envLines += "$refName=$value"
                $flatKey = ($refUri -split '/')[-1]
                $compatLines += "$flatKey=$value"
                Write-Host "OK" -ForegroundColor Green
                $resolved++
            } else {
                Write-Host "FAILED" -ForegroundColor Red
                $failed++
            }
        } catch {
            Write-Host "FAILED" -ForegroundColor Red
            $failed++
        }
    }
}

# --- Deployment secretRefs ---
if ($profile.deployments) {
    foreach ($dep in $profile.deployments.PSObject.Properties) {
        if ($dep.Value.secretRefs) {
            foreach ($ref in $dep.Value.secretRefs.PSObject.Properties) {
                Write-Host -NoNewline "  $($ref.Name)... "
                if ($DryRun) {
                    Write-Host $ref.Value
                    $resolved++
                    continue
                }
                try {
                    $value = & "$ScriptDir\Resolve-SecretRef.ps1" $ref.Value -Quiet 2>$null
                    if ($value) {
                        $envLines += "$($ref.Name)=$value"
                        $flatKey = ($ref.Value -split '/')[-1]
                        $compatLines += "$flatKey=$value"
                        Write-Host "OK" -ForegroundColor Green
                        $resolved++
                    } else {
                        Write-Host "FAILED" -ForegroundColor Red
                        $failed++
                    }
                } catch {
                    Write-Host "FAILED" -ForegroundColor Red
                    $failed++
                }
            }
        }
    }
}

# --- Write output files ---
if (-not $DryRun) {
    $envFile = Join-Path $GeneratedDir ".env"
    $compatFile = Join-Path $GeneratedDir "compat.env"
    $envLines | Set-Content -Path $envFile -Encoding UTF8
    $compatLines | Set-Content -Path $compatFile -Encoding UTF8
}

# --- FileRefs ---
if (-not $RefsOnly -and $profile.fileRefs) {
    Write-Host "`n=== Resolving fileRefs ===" -ForegroundColor Cyan
    foreach ($prop in $profile.fileRefs.PSObject.Properties) {
        $refName = $prop.Name
        $refUri = $prop.Value.uri
        $renderTo = $prop.Value.renderTo

        Write-Host -NoNewline "  $refName -> $renderTo... "
        if ($DryRun) {
            Write-Host $refUri
            $resolved++
            continue
        }
        try {
            & "$ScriptDir\Render-SecretFile.ps1" $refUri -OutputPath $renderTo 2>$null
            Write-Host "OK" -ForegroundColor Green
            $resolved++
        } catch {
            Write-Host "FAILED" -ForegroundColor Red
            $failed++
        }
    }
}

Write-Host "`n=== Summary ===" -ForegroundColor Cyan
Write-Host "Resolved: $resolved"
Write-Host "Failed:   $failed"

if ($DryRun) {
    Write-Host "This was a dry run." -ForegroundColor Yellow
} else {
    Write-Host ""
    Write-Host "Generated files:"
    Write-Host "  $(Join-Path $GeneratedDir '.env')"
    Write-Host "  $(Join-Path $GeneratedDir 'compat.env')"
}
